export const INCREMENT_COUNTER='INCREMENT_COUNTER';

export const DECREMENT_COUNTER='DECREMENT_COUNTER';

// medician

export const GET_DATA='GET_DATA';

export const ADD_DATA='ADD_DATA';

export const DELETE_DATA='DELETE_DATA';

export const LOADING_DATA='LOADING_DATA';

export const ERROR_DATA='ERROR_DATA';

export const UPDATE_DATA='UPDATE_DATA';

// patients

export const PATIENTS_GETDATA='PATIENTS_GETDATA';

export const PATIENTS_ADDDATA='PATIENTS_ADDDATA';

export const PATIENTS_DELETEDATA='PATIENTS_DELETEDATA';

export const PATIENTS_LOADINGDATA='PATIENTS_LOADINGDATA';

export const PATIENTS_ERRORDATA='PATIENTS_ERRORDATA';

export const UPDATE_PATIENTS='UPDATE_PATIENTS';

// Doctor

export const DOCTOR_GETDATA = 'DOCTOR_GETDATA'

export const DOCTOR_ADDDATA = 'DOCTOR_ADDDATA'

export const DOCTOR_DELETEDATA = 'DOCTOR_DELETEDATA'

export const DOCTOR_UPDATEDATA = 'DOCTOR_UPDATEDATA'

export const DOCTOR_LODING = 'DOCTOR_LODING'

export const DOCTOR_ERROR = 'DOCTOR_ERROR'